# Exploring Generators from the ground up
:toc: macro

toc::[]



## Introduction 

Generators allow users to program arbitrary function execution models. Whereas a typical function will always receive arguments as input and return a value as output  Generators allow the programmer to output as many or little values from a function as they wish with no requirements about when this should happen. Generators are generic enough to support modeling different kinds of problems such as asynchronous data flow, or lazy evaluation. Generators exist in several langauges including Python, Ruby, C# and JavaScript (as of 2015). A paper called "Yield: Mainstream Delimited Continuations" compares the semantics of various implementations.

This essay focuses on the JavaScript implementation and its semantics.



## From Functions

### Meet the Generator Instance

Here is one of the simplest possible functions, the `identity` function, a function that returns its argument:

[source,js]
----
function identity(x) {
  return x
}
----
----
identity('Apple')
> Apple
----

A Generator (capitalized means to say a generator function that is a factory
of generators) version of `identity` is different. It returns a constructed generator. This generator, as we will see, will also return the Generator's argument but only after a few procedures are executed.

[source,js]
----
function* IdentityGenerator(x) {
  return x
}

let generator = IdentityGenerator('Apple')
----
----
{ _:
   { _: <1>
      { next: <2>
         { value: [Function: next],
           writable: false,
           enumerable: false,
           configurable: false },
        throw: <2>
         { value: [Function: throw],
           writable: false,
           enumerable: false,
           configurable: false },
        constructor: <3>
         { value: [Function: GeneratorFunctionPrototype],
           writable: false,
           enumerable: false,
           configurable: true } } } }
----

We can learn Several things by observing the structure of a `generator`.

<1> generators have a two-level deep prototype chain. (TODO: Why?)
<2> generators have an API of two methods: `next` and `throw`.
<3> generators are instances of GeneratorFunction constructors thus with the normal caveates of `this` on its methods.

Lets explore these facts a bit more.

A `generator` is an instances of `GeneratorFunction`. We can explicitly demonstrate this fact like so:

[source,js]
----
let GeneratorFunction = Object.getPrototypeOf(function*(){}).constructor
IdentityGenerator instanceof GeneratorFunction
----
----
> true
----

Since a generator is an instance its methods are `this` sensitive. We can explicitly demonstrate this fact like so:

[source,js]
----
let generator = IdentityGenerator('Apple')
generator.next()
----
----
> { value: 'Apple', done: true }
----
[source,js]
----
let next = generator.next
next()
----
----
> TypeError: Method [Generator].prototype.next called on incompatible receiver undefined
----
----
let next = generator.next(generator)
next()
----
----
> { value: 'Apple', done: true }
----



### Meet the Container

With an instance in hand we may now use its API to accomplish our function (which is, remember, returning our argument).

There are two procedures we must execute. First we must invoke the `.next()` method to both at once "advance" the generator (mutative, more on this later) whilst returning a "generated container value" (hereafter referred to as a `container`). Then we must get the inner-value from the `container`.

1. **Generate a Container (and advance the generator)**

[source,js]
----
// ...
let container = generator.next()
----
----
{ value:
   { value: 'Apple',
     writable: true,
     enumerable: true,
     configurable: true },
  done:
   { value: true,
     writable: true,
     enumerable: true,
     configurable: true } }
----

2. **Extract the Value**

[source,js]
----
container.value
----
----
Apple
----

In sum, from the top:

[source,js]
----
// Construct a generator.       > Generate a conatiner,      >
//                              > and advance the generator. > Read the value from the container.

   IdentityGenerator('Apple')     .next()                      .value
----
----
Apple
----



### Semantics

We now have a generated value which is a container. You can see `'Apple'` at `container.value`.  The container however has another Boolean property `done`. This reflects the state of the generator; `true` means the generator has no more values to produce, `false` means the opposite. This means `generator.next()` is not a pure function. Its execution does two things: return a conatiner value (as we saw) and mutate the state of the generator that `next` is being invoked upon.

If we think about it, the mere idea/pesence of `container.done` clearly implies that there is a stateful (AKA time-sensitive) relationship between a generator and its generated container values. The relationships are thus:

. At the birth of a container value its `.done` property correctly tells us the current state of the generator. At this time, `.done` is implicitly in a state of correctness. As a generator evolves (is mutated) however, `.done` implicity changes into a stale state (AKA out-of-date, inaccurate) because its value no longer correctly reflects the state of the generator.

. There is one edge-case where the implicit state mentioned above does not apply to a container value's `.done` property; when the container value is the last value that will be generated by the generator. More specifically it is impossible for a `.done` property of value `true` to become stale, and therefore we can say it is implicitly stateless.

These two points outline the primitive/core relationship between a generator and its generated values. A user is free to build there own abstractions that create new relationships of course.

This stateful and small logical footprint tells us that generators are very much a low-level procedural construct useable as a tool for building (AKA abstracting) richer Function Oriented or Object Oriented systems/tools. Because it is low-evel the quantity divergent ideas that can be built is high. For example consider something like Koa which uses the progressive nature of generators to model HTTP Server request-response semantics versus a completely different tool js-csp which implements Communicating Sequential Processes modeled after Go channels and Clojure Core.Async.
